### ISSUE TITLE
Livros para indicar 

### ISSUE THREAD

**Issue by LuanCenci** [sillasgonzaga/literaturaBR#1]
Queria indicar o livro O Cortiço para ser adicionado ao pacote :)

**Comment by marcosvital** [comment]
@sillasgonzaga , Você prefere um issue para cada indicação, ou é melhor todos usarmos este mesmo issue?

Bom, antes de indicar livros que eu adoraria ver no pacote, gostaria de dar os parabéns pelo trabalho. Este e seus outros pacotes vão facilitar muito a vida de quer fazer textmining em português no R. :D 

**minhas indicações**

Vou começar pedindo duas das minhas obras favoritas da literatura brasileira:
- Grande Sertão: Veredas, do Guimarães Rosa;
- Vidas Secas, do Graciliano Ramos.

**Comment by sillasgonzaga** [comment]
@marcosvital, primeiramente, obrigado pelos elogios. 

Prefiro trabalhar com uma issue por livro pra controlar a demanda por livros. 

De qualquer forma, os dois livros que vc pediu infelizmente não estão em domínio público, então não posso disponibilizar no pacote. Para saber se um livro está em domínio público, vc pode consultar no dominiopublico.gov.br ou, de preferência, no Wikisource.

Já O Cortiço está sim. Vou providenciar.

**Comment by marcosvital** [comment]
Beleza! Depois confiro algum livro bacana que esteja no domínio público, e crio o issue. Valeu!

**Comment by sillasgonzaga** [comment]
@LuanCenci O Cortiço adicionado! Instale a nova versão do pacote para ter acesso ao livro.

Obrigado pela recomendação.
