### ISSUE TITLE
Indicação de livro - Noite na Taverna, Álvares de Azevedo

### ISSUE THREAD

**Issue by marcosvital** [sillasgonzaga/literaturaBR#2]
Minha indicação: Noite na Taverna, de Álvares de Azevedo.

A página na wikisource é esta: https://pt.wikisource.org/wiki/Noite_na_Taverna

**Comment by sillasgonzaga** [comment]
Feito! Atualize o pacote para ter acesso ao livro.

Dois poréns:
1 - Não extraí o texto do prefácio  
2 - Não consigo extrair as citações nos inícios dos capítulos
